language: rust
rust:
  - stable
  - beta
  - nightly
matrix:
  allow_failures:
    - rust: nightly

addons:
  apt:
    packages:
      - libsodium-dev
    sources:
      - sourceline: ppa:chris-lea/libsodium
