language: rust
rust:
  - stable
  - beta
  - nightly
os:
  - linux
cache:
  cargo: true

matrix:
  allow_failures:
    - rust: nightly
addons:
  apt:
    packages:
      - libsodium-dev
      - libelf-dev
      - libdw-dev
      - binutils-dev
      - libcurl4-openssl-dev
    sources:
      - sourceline: ppa:chris-lea/libsodium
