language: rust
rust:
  - nightly
os:
  - linux
cache:
  cargo: true
addons:
  apt:
    packages:
      - libsodium-dev
      - libelf-dev
      - libdw-dev
      - binutils-dev
      - libcurl4-openssl-dev
      - cmake
      - gcc
      - zlib1g-dev
      - libllvm4.0
    sources:
      - sourceline: ppa:chris-lea/libsodium
      - kalakris-cmake
# Add clippy
#before_script:
#  - |
#      if [[ "$TRAVIS_RUST_VERSION" == "nightly" ]]; then
#        ( ( cargo install clippy && export CLIPPY=true ) || export CLIPPY=false );
#      fi
#  - export PATH=$PATH:~/.cargo/bin
# the main build
script:
  - |
      if [[ "$TRAVIS_RUST_VERSION" == "nightly" && $CLIPPY ]]; then
        cargo clippy
      fi
  - |
      cargo build &&
      cargo test
after_success:
  - rustc -vV
  - find /usr -name "clang_rt.profile-x86_64" -exec readlink -f {} \;
  - scripts/collect-coverage
  - rm -rf target/