language: rust
rust:
  - stable
  - beta
  - nightly
os:
  - linux
  - osx

cache:
  cargo: true

matrix:
  allow_failures:
    - rust: nightly
    - os: osx

addons:
  apt:
    packages:
      - libsodium-dev
    sources:
      - sourceline: ppa:chris-lea/libsodium
before_install:
  - if [[ "$TRAVIS_OS_NAME" == "osx" ]]; then brew update          ; fi
  - if [[ "$TRAVIS_OS_NAME" == "osx" ]]; then brew install libsodium; fi
