[package]
name = "angel-whisper"
version = "0.1.0"
authors = ["vagrant"]

[dependencies]
blunder       = "0.1"
sodiumoxide   = "0.0.8"
chrono        = "0.2"
uuid          = "0.1"
bincode       = "0.4"
