#!/usr/bin/env bash

# Based on https://jbp.io/2017/07/19/measuring-test-coverage-of-rust-programs

function unit_test {
  cleanup
  cargo test --lib --no-run -- -Clink-dead-code -Zno-landing-pads -Zprofile
  sh target/debug/angel_whisper-*[^\.d]
  collect angel_whisper
}

function integration_test {
  cleanup
  cargo test $1 -- -Clink-dead-code -Zno-landing-pads -Zprofile
  collect $1
  sh target/debug/$1-*[^\.d]
}

function cleanup {
  cargo clean
  rm -rf *.gcda *.gcno
}

function collect {
  lcov \
  --gcov-tool ./scripts/llvm-gcov \
  --rc lcov_branch_coverage=1 \
  --rc lcov_excl_line=assert \
  --capture \
  --directory . \
  --base-directory . \
  -o $1.info
}
function combine_and_reduce {
  lcov \
  --gcov-tool ./scripts/llvm-gcov \
  --rc lcov_branch_coverage=1 \
  --rc lcov_excl_line=assert \
  --add angel_whisper.info \
  --add angel_system_bare.info \
  --add system-on-tokio.info \
  -o coverage.info

  lcov \
  --gcov-tool ./scripts/llvm-gcov \
  --rc lcov_branch_coverage=1 \
  --rc lcov_excl_line=assert \
  --extract coverage.info `pwd`/src/* \
  -o final.info
}


unit_test
integration_test angel_system_bare
integration_test system_on_tokio
combine_and_reduce
